
const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
const GET_POKEMON_LIST_PENDING = 'GET_POKEMON_LIST_PENDING';
const GET_POKEMON_LIST_REJECTED = 'GET_POKEMON_LIST_REJECTED';
const GET_POKEMON_LIST_FULFILLED ='GET_POKEMON_LIST_FULFILLED';

const GET_POKEMON = 'GET_POKEMON';
const GET_POKEMON_PENDING = 'GET_POKEMON_PENDING';
const GET_POKEMON_REJECTED = 'GET_POKEMON_REJECTED';
const GET_POKEMON_FULFILLED ='GET_POKEMON_FULFILLED';

const GET_POKEMON_SPECIES ='GET_POKEMON_SPECIES'
const GET_POKEMON_SPECIES_PENDING ='GET_POKEMON_SPECIES_PENDING'
const GET_POKEMON_SPECIES_REJECTED ='GET_POKEMON_SPECIES_REJECTED'
const GET_POKEMON_SPECIES_FULFILLED ='GET_POKEMON_SPECIES_FULFILLED'

const GET_POKE_DETAIL ='GET_POKE_DETAIL'
const GET_POKE_DETAIL_PENDING ='GET_POKE_DETAIL_PENDING'
const GET_POKE_DETAIL_REJECTED ='GET_POKE_DETAIL_REJECTED'
const GET_POKE_DETAIL_FULFILLED ='GET_POKE_DETAIL_FULFILLED'


const CLEAR_LIST = 'CLEAR_LIST'
const CLEAR_POKEMON='CLEAR_POKEMON'

const CLEAR_POKEMON_DETAIL='CLEAR_POKEMON_DETAIL'
const CLEAR_POKEMON_SPECIES='CLEAR_POKEMON_SPECIES'

export {
    GET_POKEMON_LIST,
    GET_POKEMON_LIST_FULFILLED,
    GET_POKEMON_LIST_PENDING,
    GET_POKEMON_LIST_REJECTED,
    CLEAR_LIST,
    GET_POKEMON,
    GET_POKEMON_PENDING,
    GET_POKEMON_REJECTED,
    GET_POKEMON_FULFILLED,
    CLEAR_POKEMON,
    GET_POKEMON_SPECIES,
    GET_POKEMON_SPECIES_PENDING,
    GET_POKEMON_SPECIES_REJECTED,
    GET_POKEMON_SPECIES_FULFILLED,
    CLEAR_POKEMON_SPECIES,
    GET_POKE_DETAIL,
    GET_POKE_DETAIL_PENDING,
    GET_POKE_DETAIL_REJECTED,
    GET_POKE_DETAIL_FULFILLED,
    CLEAR_POKEMON_DETAIL


}